//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ac
    {
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }

        public string MatKhauCu { get; set; }
        public string MatKhau1 { get; set; }
    }
}
