//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baihat
    {
        public int Id { get; set; }
        public string tenBH { get; set; }
        public int nhacS { get; set; }
        public int theL { get; set; }
    
        public virtual Nhacsi Nhacsi { get; set; }
        public virtual Theloai Theloai { get; set; }
        public virtual Nhacsi Nhacsi1 { get; set; }
        public virtual Theloai Theloai1 { get; set; }
    }
}
