//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyAN.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLAMNHACVNEntities : DbContext
    {
        public QLAMNHACVNEntities()
            : base("name=QLAMNHACVNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ac> Acs { get; set; }
        public virtual DbSet<Baihat> Baihats { get; set; }
        public virtual DbSet<Nhacsi> Nhacsis { get; set; }
        public virtual DbSet<Theloai> Theloais { get; set; }
        public virtual DbSet<thongtinnhac> thongtinnhacs { get; set; }
    }
}
