//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQuanLyAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinnhac
    {
        public string tenBH { get; set; }
        public string tenNS { get; set; }
        public string tenTL { get; set; }
    }
}
